"""EDA figures and tables from the TRAIN split only (T031).

Second-semester columns are analysis-only: plotted from the raw file in an isolated function and
saved with the `analysis_only_` prefix. Nothing here fits preprocessing or touches the test split.
"""

from __future__ import annotations

from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402
import numpy as np  # noqa: E402
import pandas as pd  # noqa: E402
import seaborn as sns  # noqa: E402

from ssn.config import Config  # noqa: E402
from ssn.features.allowlist import Allowlist  # noqa: E402
from ssn.features.engineering import (  # noqa: E402
    ENGINEERED_NAMES,
    engineer,
    zero_denominator_counts,
)

IS_DROPOUT = "is_dropout"
SOURCE_NOTE = "Source: UCI 697 (CC BY 4.0), training split only. Generated by `python -m ssn eda`."


def _save(fig: plt.Figure, path: Path) -> Path:
    fig.text(0.01, 0.005, SOURCE_NOTE, fontsize=7, color="gray")
    fig.tight_layout(rect=(0, 0.02, 1, 1))
    path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(path, dpi=130)
    plt.close(fig)
    return path


def _short(name: str) -> str:
    return name.replace("Curricular units 1st sem ", "1st sem ").replace(
        "Curricular units 2nd sem ", "2nd sem "
    )


def fig_target(train: pd.DataFrame, cfg: Config, out: Path) -> Path:
    target = cfg.get("data.target_column")
    fig, axes = plt.subplots(1, 2, figsize=(9, 3.6))
    counts = train[target].value_counts()
    axes[0].bar(counts.index, counts.values, color=["#4c72b0", "#dd8452", "#55a868"][: len(counts)])
    axes[0].set_title("Source Target (train)")
    axes[0].set_ylabel("students")
    for i, v in enumerate(counts.values):
        axes[0].text(i, v, str(v), ha="center", va="bottom", fontsize=8)
    b = train[IS_DROPOUT].value_counts().sort_index()
    axes[1].bar(["non-dropout (0)", "dropout (1)"], b.values, color=["#55a868", "#c44e52"])
    axes[1].set_title(f"Derived is_dropout (train), positive rate {train[IS_DROPOUT].mean():.3f}")
    for i, v in enumerate(b.values):
        axes[1].text(i, v, str(v), ha="center", va="bottom", fontsize=8)
    return _save(fig, out / "eda_target_distribution.png")


def fig_numeric_distributions(frame: pd.DataFrame, cols: list[str], title: str, path: Path) -> Path:
    n = len(cols)
    ncol = 4
    nrow = int(np.ceil(n / ncol))
    fig, axes = plt.subplots(nrow, ncol, figsize=(4 * ncol, 2.8 * nrow))
    for ax, col in zip(axes.flat, cols, strict=False):
        for label, color in ((0, "#55a868"), (1, "#c44e52")):
            vals = frame.loc[frame[IS_DROPOUT] == label, col].dropna()
            ax.hist(
                vals, bins=30, alpha=0.55, color=color, label=f"is_dropout={label}", density=True
            )
        ax.set_title(_short(col), fontsize=9)
        ax.tick_params(labelsize=7)
    for ax in list(axes.flat)[n:]:
        ax.axis("off")
    axes.flat[0].legend(fontsize=7)
    fig.suptitle(title, fontsize=11)
    return _save(fig, path)


def fig_categorical_dropout_rates(
    train: pd.DataFrame, allow: Allowlist, out: Path, min_n: int
) -> tuple[Path, pd.DataFrame]:
    cats = [
        c
        for c in sorted(allow.allowed_source)
        if allow.columns[c]["dtype"] in {"categorical", "binary"}
    ]
    rows = []
    for col in cats:
        codes = {int(k): v for k, v in (allow.columns[col].get("codes") or {}).items()}
        g = train.groupby(col)[IS_DROPOUT].agg(["count", "mean"]).reset_index()
        for _, r in g.iterrows():
            rows.append(
                {
                    "column": col,
                    "code": int(r[col]),
                    "label": codes.get(int(r[col]), ""),
                    "n": int(r["count"]),
                    "dropout_rate": round(float(r["mean"]), 4),
                    "reliable": int(r["count"]) >= min_n,
                }
            )
    table = pd.DataFrame(rows)
    n = len(cats)
    ncol = 3
    nrow = int(np.ceil(n / ncol))
    fig, axes = plt.subplots(nrow, ncol, figsize=(5 * ncol, 3.2 * nrow))
    for ax, col in zip(axes.flat, cats, strict=False):
        t = table[(table["column"] == col) & table["reliable"]].sort_values("dropout_rate")
        if t.empty:
            ax.axis("off")
            continue
        labels = [
            f"{c} {lab[:18]}" if lab else str(c)
            for c, lab in zip(t["code"], t["label"], strict=False)
        ]
        ax.barh(labels, t["dropout_rate"], color="#c44e52")
        ax.axvline(train[IS_DROPOUT].mean(), color="gray", ls="--", lw=1)
        ax.set_title(f"{_short(col)} (groups with n>={min_n})", fontsize=9)
        ax.tick_params(labelsize=7)
        ax.set_xlim(0, 1)
    for ax in list(axes.flat)[n:]:
        ax.axis("off")
    fig.suptitle("Dropout rate by category (train); dashed = overall rate", fontsize=11)
    return _save(fig, out / "eda_dropout_rate_by_category.png"), table


def fig_correlation(frame: pd.DataFrame, cols: list[str], out: Path) -> tuple[Path, pd.DataFrame]:
    corr = frame[cols + [IS_DROPOUT]].corr(method="spearman")
    fig, ax = plt.subplots(figsize=(0.55 * len(corr) + 3, 0.5 * len(corr) + 2))
    sns.heatmap(
        corr,
        cmap="coolwarm",
        center=0,
        vmin=-1,
        vmax=1,
        ax=ax,
        cbar_kws={"shrink": 0.6},
        xticklabels=[_short(c) for c in corr.columns],
        yticklabels=[_short(c) for c in corr.index],
    )
    ax.tick_params(labelsize=7)
    ax.set_title(
        "Spearman correlation: allowed numeric + engineered features + is_dropout (train)",
        fontsize=10,
    )
    return _save(fig, out / "eda_correlation_spearman.png"), corr


def fig_sensitive_groups(
    train: pd.DataFrame, allow: Allowlist, out: Path, min_n: int
) -> tuple[Path, pd.DataFrame]:
    """Aggregate distributions and dropout rates by sensitive attribute (audit context only)."""
    attrs = sorted(allow.sensitive)
    if "age_band" in train.columns and train["age_band"].notna().any():
        attrs = attrs + ["age_band"]
    rows = []
    for col in attrs:
        codes = {int(k): v for k, v in (allow.columns.get(col, {}).get("codes") or {}).items()}
        if col == "Age at enrollment":
            continue  # continuous; summarised via age_band and the age histogram
        g = train.groupby(col, dropna=False)[IS_DROPOUT].agg(["count", "mean"]).reset_index()
        for _, r in g.iterrows():
            key = r[col]
            label = codes.get(int(key), "") if codes and pd.notna(key) else ""
            rows.append(
                {
                    "attribute": col,
                    "group": str(key),
                    "label": label,
                    "n": int(r["count"]),
                    "share": round(int(r["count"]) / len(train), 4),
                    "dropout_rate": round(float(r["mean"]), 4),
                    "reliable": int(r["count"]) >= min_n,
                }
            )
    table = pd.DataFrame(rows)
    plot_attrs = [a for a in attrs if a != "Age at enrollment"]
    fig, axes = plt.subplots(1, len(plot_attrs) + 1, figsize=(3.6 * (len(plot_attrs) + 1), 3.6))
    for ax, col in zip(axes[:-1], plot_attrs, strict=False):
        t = table[table["attribute"] == col]
        labels = [
            f"{g}{(' ' + lab[:12]) if lab else ''}\n(n={n})"
            for g, lab, n in zip(t["group"], t["label"], t["n"], strict=False)
        ]
        colors = ["#c44e52" if r else "#cccccc" for r in t["reliable"]]
        ax.bar(labels, t["dropout_rate"], color=colors)
        ax.axhline(train[IS_DROPOUT].mean(), color="gray", ls="--", lw=1)
        ax.set_ylim(0, 1)
        ax.set_title(_short(col), fontsize=9)
        ax.tick_params(labelsize=6, rotation=0)
    ax = axes[-1]
    ax.hist(train["Age at enrollment"], bins=range(16, 72, 2), color="#4c72b0")
    ax.set_title("Age at enrollment (train)", fontsize=9)
    ax.set_xlabel("age")
    fig.suptitle(
        f"Sensitive attributes: dropout rate by group (grey = n<{min_n}); aggregate audit context only",
        fontsize=10,
    )
    return _save(fig, out / "eda_sensitive_groups.png"), table


def fig_analysis_only_second_semester(raw: pd.DataFrame, cfg: Config, out: Path) -> Path:
    """ANALYSIS ONLY: second-semester distributions from the raw file. Never a model input."""
    target = cfg.get("data.target_column")
    cols = [c for c in raw.columns if c.startswith("Curricular units 2nd sem")]
    fig, axes = plt.subplots(2, 3, figsize=(13, 6))
    for ax, col in zip(axes.flat, cols, strict=False):
        for label, color in (
            ("Dropout", "#c44e52"),
            ("Enrolled", "#dd8452"),
            ("Graduate", "#55a868"),
        ):
            ax.hist(
                raw.loc[raw[target] == label, col],
                bins=25,
                alpha=0.5,
                color=color,
                label=label,
                density=True,
            )
        ax.set_title(_short(col), fontsize=9)
        ax.tick_params(labelsize=7)
    axes.flat[0].legend(fontsize=7)
    fig.suptitle(
        "ANALYSIS ONLY - second-semester columns are prohibited model inputs (post prediction point)",
        fontsize=10,
        color="#a00000",
    )
    return _save(fig, out / "analysis_only_second_semester_distributions.png")


def run_eda(
    train: pd.DataFrame, raw: pd.DataFrame, cfg: Config, allow: Allowlist
) -> dict[str, Path]:
    figs = cfg.path_for("reports_dir") / "figures"
    tables = cfg.path_for("reports_dir") / "tables"
    tables.mkdir(parents=True, exist_ok=True)
    min_n = int(cfg.get("fairness.min_group_size"))

    eng = engineer(train)
    frame = pd.concat([train, eng], axis=1)
    numeric_allowed = sorted(
        c for c in allow.allowed_source if allow.columns[c]["dtype"] == "numeric"
    )

    written: dict[str, Path] = {}
    written["target"] = fig_target(train, cfg, figs)
    written["numeric_source"] = fig_numeric_distributions(
        frame,
        numeric_allowed,
        "Allowed numeric source features by is_dropout (train)",
        figs / "eda_numeric_source_by_target.png",
    )
    written["numeric_engineered"] = fig_numeric_distributions(
        frame,
        ENGINEERED_NAMES,
        "Engineered first-semester features by is_dropout (train)",
        figs / "eda_engineered_by_target.png",
    )
    written["categorical"], cat_table = fig_categorical_dropout_rates(train, allow, figs, min_n)
    written["correlation"], corr = fig_correlation(frame, numeric_allowed + ENGINEERED_NAMES, figs)
    written["sensitive"], sens_table = fig_sensitive_groups(train, allow, figs, min_n)
    written["analysis_only_sem2"] = fig_analysis_only_second_semester(raw, cfg, figs)

    # tables
    summary_rows = []
    for col in numeric_allowed + ENGINEERED_NAMES:
        for label in (0, 1):
            s = frame.loc[frame[IS_DROPOUT] == label, col]
            summary_rows.append(
                {
                    "feature": col,
                    "is_dropout": label,
                    "n": int(s.notna().sum()),
                    "mean": round(float(s.mean()), 4),
                    "median": round(float(s.median()), 4),
                    "std": round(float(s.std()), 4),
                    "n_missing": int(s.isna().sum()),
                }
            )
    pd.DataFrame(summary_rows).to_csv(tables / "eda_numeric_summary_by_target.csv", index=False)
    cat_table.to_csv(tables / "eda_dropout_rate_by_category.csv", index=False)
    sens_table.to_csv(tables / "eda_dropout_rate_by_sensitive_group.csv", index=False)
    corr[IS_DROPOUT].drop(IS_DROPOUT).sort_values().rename("spearman_with_is_dropout").to_csv(
        tables / "eda_spearman_with_target.csv"
    )
    zero_denominator_counts(train).to_csv(tables / "zero_denominators.csv", index=False)
    age = train["Age at enrollment"]
    pd.DataFrame(
        {
            "statistic": ["n", "min", "p10", "p25", "median", "p75", "p90", "max", "mean"],
            "value": [
                len(age),
                age.min(),
                age.quantile(0.1),
                age.quantile(0.25),
                age.median(),
                age.quantile(0.75),
                age.quantile(0.9),
                age.max(),
                round(float(age.mean()), 3),
            ],
        }
    ).to_csv(tables / "eda_age_summary.csv", index=False)
    if "age_band" in train.columns and train["age_band"].notna().any():
        train.groupby("age_band", dropna=False)[IS_DROPOUT].agg(
            n="count", dropout_rate="mean"
        ).round(4).to_csv(tables / "eda_age_band_counts.csv")
    return written
